version: "3.8"

services:
  backend:
    build: 
      context: ./backend
      target: development
    command: go run main.go
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/quantumbe-21866-firebase-adminsdk-fbsvc-ae3a530754.json
    env_file:
      - .env


  frontend:
    build:
      context: ./frontend
      target: development
    working_dir: /app
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
